### ISSUE TITLE
원격사이트 추가요청사항

### ISSUE THREAD

**Issue by iuje** [clipsoftgithub/RSA#1]
1.개발자,사용자 목록추가
2. 개발자일 경우 서버,디자이너,뷰어 구분추가
3.제품명에서 클립리포트데몬 추가
4. 사용자일 경우 이름부분 필수항목에서 제외
5. 접수창에서 제품명 입력후 진행사항으로 가면 초기화되는 현상

위의 5가지 사항 요청드립니다.
감사합니다. ^^

**Comment by clipsoftgithub** [comment]
추가 요청사항은 다음 패치 때 반영하겠습니다.

**Comment by clipsoftgithub** [comment]
2017년 8월 22일 패치함.
