### ISSUE TITLE
진행에서 수정이 안되요

### ISSUE THREAD

**Issue by iuje** [clipsoftgithub/RSA#10]
진행 탭에서 진행이되지 않아요 ㅠㅠ 
수정부탁드립니다.

**Comment by clipsoftgithub** [comment]
오키바리..수정하겠음

**Comment by clipsoftgithub** [comment]
9월 13일에 패치함 - [1.0.0.5](https://github.com/clipsoftgithub/RSA/releases/tag/1.0.0.5)
