### ISSUE TITLE
조회시 날짜로 조회가능하게 해주세요

### ISSUE THREAD

**Issue by iuje** [clipsoftgithub/RSA#4]
검색할때 날짜로도 가능하게 해주세요^^

**Comment by clipsoftgithub** [comment]
다음 패치때 적용하겠음...^^

**Comment by clipsoftgithub** [comment]
2017년 8월 22일 패치함.
[https://github.com/clipsoftgithub/RSA/tree/blueeyes/hotfix/issue4](https://github.com/clipsoftgithub/RSA/tree/blueeyes/hotfix/issue4)
