### ISSUE TITLE
완료페이지에서 수정,삭제버튼요청

### ISSUE THREAD

**Issue by iuje** [clipsoftgithub/RSA#5]
완료페이지 부분에서 수정하고 삭제버튼 요청드립니다. ^^

**Comment by clipsoftgithub** [comment]
다음 패치때 적용하겠음...^^

**Comment by clipsoftgithub** [comment]
8월 24일 패치함.
[https://github.com/clipsoftgithub/RSA/tree/blueeyes/feature/issue5](https://github.com/clipsoftgithub/RSA/tree/blueeyes/feature/issue5)
