### ISSUE TITLE
지원시작버튼과 종료버튼

### ISSUE THREAD

**Issue by iuje** [clipsoftgithub/RSA#6]
사용자일 경우에 접수시간이 길어질수 있어서 지원시작버튼과 종료버튼 요청드립니다.

**Comment by clipsoftgithub** [comment]
다음 패치때 적용하겠음...^^

**Comment by clipsoftgithub** [comment]
8월 24일 패치함.
[https://github.com/clipsoftgithub/RSA/tree/blueeyes/feature/issue6](https://github.com/clipsoftgithub/RSA/tree/blueeyes/feature/issue6)
