### ISSUE TITLE
검색조건

### ISSUE THREAD

**Issue by iuje** [clipsoftgithub/RSA#8]
검색에서 시작일과 종료일 둘다 적용되게 해주세요^^

**Comment by clipsoftgithub** [comment]
지금은 아래처럼 작동해야 정상임(안되면 버그로 볼 수 있음).

시작일 | 종료일 | 결과
--- | --- | ---
O  |  O |  시작일과 종료일 사이의 데이터 검색
O  | X | 시작일에 설정한 날짜 이후 모든 데이터 검색
X  | O | 종료일에 설정한 날짜 이전 모든 데이터 검색
X  | X | 검색 안됨

어떻게 검색되면 되는건지 자세한 설명이 필요함.

**Comment by clipsoftgithub** [comment]
종료일이 적용 안되고 있다면 버그임. 테스트 해보고 확인되면 버그 패치하겠음.

**Comment by clipsoftgithub** [comment]
8월 31일 패치함.
